language: java
jdk:
- oraclejdk8

dist: xenial
addons:
  snaps:
    - name: aws-cli
      confinement: classic

before_install:
  - pip install aws-sam-cli --user

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:

    - stage: build
      script:
      - mvn test
      - mvn package shade:shade

    - stage: deploy
      script:
      - aws --version
      - sam --version
      - sam validate
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket $BUCKET_NAME
      - sam deploy --template-file packaged.yaml --capabilities CAPABILITY_IAM --stack-name $STACK_NAME
