language: java
jdk:
- oraclejdk8

dist: xenial
addons:
  snaps:
    - name: aws-cli
      confinement: classic

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:

    - stage: build
      script:
      - mvn test
      - mvn package shade:shade

    - stage: deploy
      script:
      - aws --version
